config/routes.rb
Rails.application.routes.draw do
	resources :publications, :only => [:index, :show] # techlab_cms generated

	#Casein routes
	namespace :casein, path: 'admin' do
		resources :publications
		resources :readings
	end

	resources :readings, :only => [:index, :show] # techlab_cms generated
  get 'search', to: 'search#index', as: 'search'
  get 'tag/:tag', to: 'tags#show', as: 'tag'
  root to: 'visitors#index'
  mount Bootsy::Engine => '/bootsy', as: 'bootsy'
end

app/models/publication.rb
class Publication < ActiveRecord::Base
  include Bootsy::Container
  searchkick
  mount_uploader :file, DocumentUploader

  def file_viewer(root)
    return nil if file.nil?
    if file.file.extension == 'pdf'
      {type: 'pdf' , src: file.url}
    else
      {type: file.file.extension , src: "https://docs.google.com/viewer?url=#{root}#{file.url}&embedded=true"}
    end
  end

  def path
    self
  end
end

app/controllers/casein/publications_controller.rb
# Scaffolding generated by Casein v1.3.3.7

module Casein
  class PublicationsController < Casein::CaseinController

    ## optional filters for defining usage according to Casein::AdminUser access_levels
    # before_filter :needs_admin, :except => [:action1, :action2]
    # before_filter :needs_admin_or_current_user, :only => [:action1, :action2]
  
    def index
      @casein_page_title = 'Publications'
      @publications = Publication.order(sort_order(:title)).paginate :page => params[:page]
    end
  
    def show
      @casein_page_title = 'View publication'
      @publication = Publication.find params[:id]
      @tags = @publication.tags.split(', ')
    end
  
    def new
      @casein_page_title = 'Add a new publication'
      @publication = Publication.new
    end

    def create
      @publication = Publication.new publication_params

      @publication.tags = publication_tags.join(', ')

      if @publication.save
        Tag.update_and_clean([], publication_tags)

        flash[:notice] = 'Publication created'
        redirect_to casein_publications_path
      else
        flash.now[:warning] = 'There were problems when trying to create a new publication'
        render :action => :new
      end
    end

    def update
      @casein_page_title = 'Update publication'

      @publication = Publication.find params[:id]
      old_tags = @publication.tags.split(', ')
      @publication.tags = publication_tags.join(', ')

      if @publication.update_attributes publication_params
        Tag.update_and_clean(old_tags, publication_tags)
        flash[:notice] = 'Publication has been updated'
        redirect_to casein_publications_path
      else
        flash.now[:warning] = 'There were problems when trying to update this publication'
        render :action => :show
      end
    end

    def destroy
      @publication = Publication.find params[:id]
      Tag.update_and_clean(@publication.tags.split(', '), [])
      @publication.destroy
      flash[:notice] = 'Publication has been deleted'
      redirect_to casein_publications_path
    end

    private
      
      def publication_params
        params.require(:publication).permit(:bootsy_image_gallery_id, :title, :content, :tags, :file)
      end

      def publication_tags
        if params[:publication][:tags]
          params[:publication][:tags].delete_if { |t| t.blank? }
        else
          []
        end
      end
  
  end
end

app/controllers/casein/readings_controller.rb
# Scaffolding generated by Casein v1.3.3.7

module Casein
  class ReadingsController < Casein::CaseinController

    ## optional filters for defining usage according to Casein::AdminUser access_levels
    # before_filter :needs_admin, :except => [:action1, :action2]
    # before_filter :needs_admin_or_current_user, :only => [:action1, :action2]
  
    def index
      @casein_page_title = 'Readings'
      @readings = Reading.order(sort_order(:title)).paginate :page => params[:page]
    end
  
    def show
      @casein_page_title = 'View reading'
      @reading = Reading.find params[:id]
      @tags = @reading.tags.split(', ')
    end
  
    def new
      @casein_page_title = 'Add a new reading'
      @reading = Reading.new
    end

    def create
      @reading = Reading.new reading_params

      @reading.tags = reading_tags.join(', ')

      if @reading.save
        Tag.update_and_clean([], reading_tags)

        flash[:notice] = 'Reading created'
        redirect_to casein_readings_path
      else
        flash.now[:warning] = 'There were problems when trying to create a new reading'
        render :action => :new
      end
    end

    def update
      @casein_page_title = 'Update reading'

      @reading = Reading.find params[:id]
      old_tags = @reading.tags.split(', ')
      @reading.tags = reading_tags.join(', ')

      if @reading.update_attributes reading_params
        Tag.update_and_clean(old_tags, reading_tags)
        flash[:notice] = 'Reading has been updated'
        redirect_to casein_readings_path
      else
        flash.now[:warning] = 'There were problems when trying to update this reading'
        render :action => :show
      end
    end

    def destroy
      @reading = Reading.find params[:id]
      Tag.update_and_clean(@reading.tags.split(', '), [])
      @reading.destroy
      flash[:notice] = 'Reading has been deleted'
      redirect_to casein_readings_path
    end

    private
      
      def reading_params
        params.require(:reading).permit(:bootsy_image_gallery_id, :title, :content, :tags, :file)
      end

      def reading_tags
        if params[:reading][:tags]
          params[:reading][:tags].delete_if { |t| t.blank? }
        else
          []
        end
      end
  
  end
end

app/controllers/publications_controller.rb
class PublicationsController < ApplicationController
  before_action :set_post, only: [:show]

  def index
    @publications = Publication.paginate(page: params[:page], per_page: 5).order('created_at DESC')
    respond_to do |format|
      format.html
      format.js
    end
  end

  def show
    @file_viewer = @publication.file_viewer("#{request.protocol}#{request.host}:#{request.port}")
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_post
    @publication = Publication.find(params[:id])
  end
end

app/helpers/casein/config_helper.rb
module Casein
  module ConfigHelper
    
    # Name of website or client — used throughout Casein.
    def casein_config_website_name
      'Casein'
    end

    # Filename of logo image. Ideally, it should be a transparent PNG around 140x30px
    def casein_config_logo
      'casein/casein.png'
    end

    # The server hostname where Casein will run
    def casein_config_hostname
      if Rails.env.production?
        'http://www.caseincms.com'
      else
        'http://0.0.0.0:3000'
      end
    end

    # The sender address used for email notifications
    def casein_config_email_from_address
      'donotreply@caseincms.com'
    end
  
    # The initial page the user is shown after they sign in or click the logo. Probably this should be set to the first tab.
    # Do not point this at casein/index!
    def casein_config_dashboard_url
      url_for :controller => :casein, :action => :blank
    end
  
    # A list of stylesheets to include. Do not remove the core casein/casein, but you can change the load order, if required.
    def casein_config_stylesheet_includes
      %w[casein/casein casein/custom]
    end
  
    # A list of JavaScript files to include. Do not remove the core casein/casein, but you can change the load order, if required.
    def casein_config_javascript_includes
      %w[casein/casein casein/custom]
    end
    
  end
end

app/views/casein/publications/_form.html.erb
<!-- Scaffolding generated by Casein v1.3.3.7 -->




	
		
		<div class="row">
		  <div class="col-lg-12">
			<%= casein_text_field f, f.object, :title %>
			</div>
		</div>
		
		
	

	
		
		
		
		
	

	
		
		<div class="row">
		  <div class="col-lg-12">
				<label class="control-label" for="tags">Tags</label>
				<%= f.select :tags, options_for_select(Tag.all.pluck(:name), @tags), {}, { class: 'form-control', id: 'tags', multiple: ''} %>
		  </div>
			<script>
			$( "#tags" ).select2({
				tags: true,
  			tokenSeparators: [',', ' '],
				theme: "bootstrap"
			});
			</script>
		</div>
		
		
	

	
		
			
		
		
	



<div class="row">
  <div class="col-lg-12">

		<!-- Nav tabs -->
		<ul class="nav nav-tabs" role="tablist">
			<li role="presentation" class="active"><a href="#text" id="text-tab-btn" aria-controls="text" role="tab" data-toggle="tab">Text Content</a></li>
			<li role="presentation"><a href="#upload" id="upload-tab-btn" aria-controls="upload" role="tab" data-toggle="tab">Upload PDF or Doc</a></li>
		</ul>

		<!-- Tab panes -->
		<div class="tab-content">
			<div role="tabpanel" class="tab-pane active" id="text">
				<%= f.bootsy_area :content, editor_options: { html: true }, class: "form-control", rows: 15, cols: 10 %>
			</div>
			<div role="tabpanel" class="tab-pane" id="upload">
				<small>Click "Choose File" or drag and drop your file into the box below. You can only upload a .pdf, .doc or .docx file.</small>
				<%= f.file_field :file, class: "dropzone", id: "file-uploader" %>
			</div>
		</div>


  </div>
</div>

app/views/casein/publications/_table.html.erb
<!-- Scaffolding generated by Casein v1.3.3.7 -->

<table class="table table-striped table-hover table-condensed">
	<thead>
		<tr>
			<th><%= casein_sort_link "Title", :title %></th>
			<th><%= casein_sort_link "Content", :content %></th>
			<th><%= casein_sort_link "Tags", :tags %></th>
			<th><%= casein_sort_link "File", :file %></th>
			<th>&nbsp;</th>
		</tr>
	</thead>
	
	<% publications.each do |publication| %>
		<tr>
			<td><%= casein_table_cell_link publication.title, casein_publication_path(publication) %></td>
			<td><%= casein_table_cell_link publication.content, casein_publication_path(publication) %></td>
			<td><%= casein_table_cell_link publication.tags, casein_publication_path(publication) %></td>
			<td><%= casein_table_cell_link publication.file, casein_publication_path(publication) %></td>
			<td class="delete">
				<%= link_to(casein_show_row_icon("trash"), casein_publication_path(publication), :method => :delete, :data => { :confirm => "Are you sure you want to delete this publication?" }) %>
			</td>
		</tr>
	<% end %>
</table>

app/views/casein/publications/index.html.erb
<!-- Scaffolding generated by Casein v1.3.3.7 -->

<h2>Publications<%= casein_pagination_details @publications %></h2>

<%= render :partial => 'casein/publications/table', :locals => { :publications => @publications } %>

<div class="text-center">
	<%= will_paginate @publications %>
</div>

<%= content_for :sidebar do %>

	<li><%= link_to "#{casein_show_icon "plus-sign"}Add a new publication".html_safe, new_casein_publication_path %></li>

<% end %>

app/views/casein/publications/new.html.erb
<!-- Scaffolding generated by Casein v1.3.3.7 -->

<h2>Add a new publication</h2>

<%= form_for @publication, :url => casein_publications_path do |f| %>
	
	<%= render :partial => 'casein/publications/form', :locals => { :f => f } %>
	
	<p class="submits">
		<%= link_to 'Cancel', casein_publications_path, :class => 'btn btn-mini btn-danger' %>
		<%= f.submit "Add new publication", :class => "btn btn-mini btn-primary" %>
	</p>

<% end %>

<%= content_for :sidebar do %>
	<li><%= link_to "#{casein_show_icon "th-list"}Back to list".html_safe, casein_publications_path %></li>
<% end %>

app/views/casein/publications/show.html.erb
<!-- Scaffolding generated by Casein v1.3.3.7 -->

<h2>View publication</h2>

<%= form_for @publication, :url => casein_publication_path(@publication) do |f| %>

	<%= render :partial => 'casein/publications/form', :locals => { :f => f } %>
	
	<p class="submits">
	  	<%= link_to 'Cancel', casein_publications_path, :class => 'btn btn-mini btn-danger' %>
		<%= f.submit "Save changes", :class => "btn btn-mini btn-primary" %>
	</p>

<% end %>

<%= content_for :sidebar do %>
	<li><%= link_to "#{casein_show_icon "th-list"}Back to list".html_safe, casein_publications_path %></li>
<% end %>