config/routes.rb
Rails.application.routes.draw do
	resources :publications, :only => [:index, :show] # techlab_cms generated

	#Casein routes
	namespace :casein, path: 'admin' do
		resources :publications
		resources :readings
	end

	resources :readings, :only => [:index, :show] # techlab_cms generated
  get 'search', to: 'search#index', as: 'search'
  get 'tag/:tag', to: 'tags#show', as: 'tag'
  root to: 'visitors#index'
  mount Bootsy::Engine => '/bootsy', as: 'bootsy'
end

app/views/layouts/_content.html.erb
<div class="content">
  <% posts.each do |post| %>
  <article class="post type-post status-publish format-standard has-post-thumbnail hentry" itemscope="">
    <header class="post-head">
      <time class="post-date" datetime="<%= post.created_at %>" itemprop="datePublished"><%= post.created_at.strftime('%A, %d %b %Y') %></time><!-- /.post-date -->
      <h3 class="post-title">
        <%= link_to post.title, post.path, title: post.title %>
      </h3><!-- /.post-title -->

      <ul class="post-category">
        <% if @is_home || @is_search %>
          <li><%= link_to post.model_name.pluralize, send("#{post.model_name.pluralize.downcase}_path") %></li>
        <% end %>
      </ul>
    </header><!-- /.post-head -->

    <div class="post-meta">
    </div><!-- /.post-meta -->

    <div class="post-body">
      <div class="entry" itemprop="articleBody">
        <p>
          <% unless post.content.nil? %>
            <%= truncate_html(post.content, length: 500, omission: '...(continued)').html_safe %>
          <% end %>
        </p>
      </div><!-- /.entry -->

      <div class="entry">
        <% unless post.tags.nil? %>
          <% post.tags.split(', ').each do |tag| %>
            <%= link_to tag, tag_path(tag) %>
          <% end %>
        <% end %>
      </div>

      <div class="post-actions">
        <%= link_to 'Read more', post.path, class: 'button tiny grey' %>
      </div><!-- /.post-actions -->
    </div><!-- /.post-body -->
  </article>
  <% end %>
</div>

app/views/layouts/_footer.html.erb
<footer>
  <div class="footer-body text-center">
    <p class="lead text-center" style="margin-right: 10px; margin-bottom: 10px; font-size: 12px;">The Online Resource Portal was made with <i class="fa fa-heart heart-color"></i> by the <a href="http://techlab.works" class="text-white btn-track" data-location="top" data-event="CodersClan_Link_Click" target="_blank">TechLab</a></p>
  </div>
</footer>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default navbar-static-top top-bar">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <h1>
        <%= link_to 'kanri-kirai', root_path, class: 'navbar-brand', id: 'site-title' %>
      </h1>
      <br>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<li><%= link_to 'Home', root_path %></li>
<!-- SCAFFOLD_INSERT -->
<li><%= link_to "Publications", publications_path %></li>
<li><%= link_to "Readings", readings_path %></li>

app/views/layouts/_show_content.html.erb
<div class="content">
    <article class="post type-post status-publish format-standard has-post-thumbnail hentry" itemscope="">
      <header class="post-head">
        <%= link_to 'Back', 'javascript:history.go(-1);', class: 'pull-left back-btn' %><br>
        <time class="post-date" datetime="<%= post.created_at %>" itemprop="datePublished"><%= post.created_at.strftime('%A, %d %b %Y') %></time><!-- /.post-date -->
        <h3 class="post-title">
          <%= post.title %>
        </h3><!-- /.post-title -->

        <ul class="post-category">
            <li><%= link_to post.class.name.pluralize, send("#{post.class.name.pluralize.downcase}_path") %></li>
        </ul>

      </header><!-- /.post-head -->

      <div class="post-meta">
      </div><!-- /.post-meta -->

      <div class="post-body">
        <div class="entry" itemprop="articleBody">
          <p>
            <% unless post.content.nil? %>
              <%= post.content.html_safe %>
            <% end %>
            <% unless file.nil? %>
              <% if file[:type] == 'pdf' %>
              <object class="pdf-viewer" data="<%= file[:src] %>" type="application/pdf">
                <embed src="<%= file[:src] %>" type="application/pdf" />
              </object>
              <% else %>
              <iframe src="<%= file[:src] %>" class="pdf-viewer" frameborder="0"></iframe>
              <% end %>
            <% end %>
          </p>
        </div><!-- /.entry -->

        <div class="entry">
          <%= post.tags %>
        </div>

      </div><!-- /.post-body -->
    </article>
</div>

app/views/layouts/_sidebar.html.erb
<div class="sidebar">
  <aside id="search-2" class="widget widget_search">
    <div class="widget-title"><h3 class="widgettitle">Search</h3></div>
    <%= simple_form_for @search, url: search_path, method: :get do |f| %>
      <%= f.input :query, label: false, placeholder: 'What are you looking for?' %>
      <%= f.select :categories, CMS_MODELS.map.with_index{|c, i| [c.name, i]}, {selected: @search.categories} , {class:'form-control', id: 'category-select', multiple: 'multiple'} %>
      <%= f.select :tags, Tag.all.map{|t| [t.name, t.name]}, {}, {class:'form-control', id: 'tag-select', multiple: 'multiple'} %>
      <%= f.button :submit, 'Search', class:'btn btn-defaut btn-block', id: 'search-btn' %>
    <% end %>
  </aside>
  <aside id="recent-posts" class="widget widget_recent_entries">
    <div class="widget-title"><h3 class="widgettitle">Recent Posts</h3></div>
    <ul class="list">
      <% @recent_content.each do |content| %>
        <li>
          <%= link_to content.title, content.path %>
        </li>
      <% end %>
    </ul>
  </aside>
  <aside id="tag_cloud-3" class="widget widget_tag_cloud">
    <div class="widget-title"><h3 class="widgettitle">Tag Cloud</h3></div>
    <div class="tagcloud">
      <% Tag.all.pluck(:name).each do |tag| %>
        <%= link_to tag, tag_path(tag) %>
      <% end %>
    </div>
  </aside>
</div>

<script>
$(function() {
    $('.sidebar').parent().theiaStickySidebar();

    $("#category-select").select2({
      placeholder: "Categories"
    });
    $("#tag-select").select2({
      placeholder: "Tags"
    });
});
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "kanri-kirai" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "kanri-kirai" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
  <div class="wrapper">
    <header class="header">
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
    <%= render partial: 'layouts/footer'%>
  </div>
  </body>
</html>